name: CI/CD with AWS CodeDeploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Deploy to AWS EC2 with CodeDeploy
      run: |
        aws deploy create-deployment --region your-aws-region --application-name your-codedeploy-application-name --deployment-group-name your-codedeploy-group-name --s3-location bucket=your-s3-bucket-name,key=your-s3-key,bundleType=zip

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
